name = "nano-banana-workers-bot"
main = "src/index.ts"
compatibility_date = "2026-02-10"

[[d1_databases]]
binding = "DB"
database_name = "nano-banana-bot"
database_id = "f8947b9c-3f2f-49fa-89c9-932bb4b07552"

[[queues.producers]]
binding = "BOT_JOBS"
queue = "nano-banana-bot-jobs"

[[queues.consumers]]
queue = "nano-banana-bot-jobs"
max_batch_size = 10
max_batch_timeout = 5

[vars]
YOOKASSA_API_BASE_URL = "https://api.yookassa.ru/v3"
YOOKASSA_RECEIPT_VAT_CODE = "1"
YOOKASSA_RECEIPT_PAYMENT_MODE = "full_prepayment"
YOOKASSA_RECEIPT_PAYMENT_SUBJECT = "service"
