export interface Env {
  DB: D1Database;
  BOT_JOBS: Queue;

  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET: string;
  TELEGRAM_WEBHOOK_HEADER_SECRET: string;

  LAOZHANG_PER_REQUEST_API_KEY: string;
  LAOZHANG_PER_USE_API_KEY: string;

  YOOKASSA_SHOP_ID: string;
  YOOKASSA_SECRET_KEY: string;
  YOOKASSA_API_BASE_URL?: string;
  YOOKASSA_RECEIPT_EMAIL: string;
  YOOKASSA_RECEIPT_VAT_CODE?: string;
  YOOKASSA_RECEIPT_PAYMENT_MODE?: string;
  YOOKASSA_RECEIPT_PAYMENT_SUBJECT?: string;

  TELEGRAM_BOT_USERNAME?: string;
  SUPPORT_USERNAME: string;
  MENU_BANNER_URL?: string;
}
